export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const CHANGE_ROBOTS_PENDING = "CHANGE_ROBOTS_PENDING";
export const CHANGE_ROBOTS_SUCCESS = "CHANGE_ROBOTS_SUCCESS";
export const CHANGE_ROBOTS_ERROR = "CHANGE_ROBOTS_ERROR";
